version: "3.8"

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "8000:5000"
    volumes:
      - gerenciamento_data:/data
    environment:
      - DATABASE_URL=sqlite:////data/gerenciamento.db
    networks:
      - microservicos_network

  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "8001:5000"
    volumes:
      - reservas_data:/data
    environment:
      - DATABASE_URL=sqlite:////data/reservas.db
      - GERENCIAMENTO_URL=http://gerenciamento:8000
    depends_on:
      - gerenciamento
    networks:
      - microservicos_network

  atividades:
    build: ./atividades
    container_name: atividades
    ports:
      - "8002:5000"
    volumes:
      - atividades_data:/data
    environment:
      - DATABASE_URL=sqlite:////data/atividades.db
      - GERENCIAMENTO_URL=http://gerenciamento:8000
    depends_on:
      - gerenciamento
    networks:
      - microservicos_network

volumes:
  gerenciamento_data:
  reservas_data:
  atividades_data:

networks:
  microservicos_network:
    driver: bridge
